version: '3'
services:
#  cats-postgres:
#    image: postgres
#    container_name: cats-postgres
#    restart: always
#    ports:
#      - "5431:5431"
#    command: -p 5431
#    expose:
#      - "5431"
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_USER: cats
#      POSTGRES_DB: cats-api

  eureka-server:
    image:  registry.hub.docker.com/jirafus400/cats-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: registry.hub.docker.com/jirafus400/cats-gateway-demo:latest
    container_name: api-gateway
    ports:
      - "9191:9191"
    expose:
      - "9191"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    depends_on:
      - eureka-server

  cats-api:
    image: registry.hub.docker.com/jirafus400/cats-api-demo-k8s:latest
    container_name: cats-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
