apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cats-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demo-cats.internal
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cats-api
                port:
                  number: 80